pharmquest/src/components/layout/Header.tsx, pharmquest/src/pages/index.tsx, pharmquest/src/pages/map/index.tsx
- 헤더 구현
- 피그마에서 전체 width는 1440px이었는데 화면에 맞춰 w-full로 변경함
- 로고 타입 버튼의 width가 127px인데 레이아웃을 맞추니 글자가 오버되어 w-[155px]로 변경함
체크 리스트의 내용이 피그마에서 제가 임의로 변경한 내용(디자인)인데 괜찮은지 봐주시면 감사하겠습니다.
=> [feat/#4] 헤더 구현 완료

pharmquest/src/components/layout/Header.tsx, pharmquest/src/pages/map/index.tsx
- closed #17
- 헤더 추가
- 검색 창 추가(아직 약국 정보가 없어서 ui만 하드코딩한 상태)
- 경로 이모티콘은 받아서 추가 예정
- 접으면 아래처럼 보임
=> [feat/#17] 약국 찾기 ui 구현

pharmquest/src/components/layout/Header.tsx, pharmquest/src/pages/index.tsx, pharmquest/src/pages/map/index.tsx
=> [feat/#20] 메인 화면 구현

pharmquest/src/components/layout/Header.tsx, pharmquest/src/pages/index.tsx, pharmquest/src/pages/map/index.tsx
- closed #20
- 메인 화면 디자인 조정
- 헤더 디자인 조정
- 약국 찾기 디자인 조정
로그인 전
로그인 후(임의로 마이페이지 버튼을 로그아웃 버튼으로 사용함~)
접기 전(지도 관련 api 아직 안 들어왔기에 지도 사진은 생략함~)
접은 후
=> [feat/#20] 마진 등 디자인 수정

src/pages/_app.tsx, src/pages/supplements/components/SupplementCard.tsx, src/pages/supplements/index.tsx
- closed #30
- 배포 버그 수정
- 웹사이트 title 및 SEO 설정
=> [fix#30] 배포 설정 및 title/SEO 설정

next.config.ts, package.json, pnpm-lock.yaml, public/svgs/index.ts, src/pages/community/components/NavbarItem.tsx, src/pages/community/components/PopularPostItem.tsx, src/pages/supplements/components/SupplementCard.tsx, src/pages/supplements/index.tsx, tsconfig.json
- closed #32 
- svgr 패키지 설치 및 설정
=> [feat/#32] svgr 설정

public/svgs/index.ts, public/svgs/map-pin.svg, public/svgs/search-bar.svg, public/svgs/search.svg, public/svgs/x.svg, src/components/common/FilterButton.tsx, src/components/common/Search.tsx, src/components/layout/Header.tsx, src/pages/index.tsx
- closed #49 
- Search 컴포넌트 style 수정
- FilterButton 홈에서의 style 수정
- header 배치 및 style 조정
- Search 컴포넌트에서 국가 선택(dropdown)은 아직 추가하지 않았습니다.
=> [feat#49] 공용 컴포넌트 수정

src/components/common/FilterButton.tsx
- closed #57
- 메인에서 필터버튼 누르면 흰색 배경으로
=> [feat/#57] 메인 화면 기준 필터버튼 클릭 시 배경 흰색으로

public/svgs/index.ts
=> :fire: index.ts의 겹치는 아이콘 코드 삭제

src/components/layout/Footer.tsx, src/pages/index.tsx
- closed #20
- 커뮤니티 간격 줄여달라는 요청 들어왔음
- 커뮤니티와 푸터 간의 간격을 두는데 푸터 대신 메인에서 설정
디자이너님이 요청주신대로 화면 수정하고 소현님께 확인받음
=> [feat/#20] 커뮤니티랑 푸터 수정

next.config.ts, src/apis/axios-instance.ts, src/hooks/community/usePostMutation.ts, src/hooks/community/useUserCount.ts, src/pages/community/create/index.tsx, src/pages/community/modify/[postId]/index.tsx, src/pages/community/post/[postId]/index.tsx, src/pages/community/post/components/CommentInput.tsx, src/pages/community/post/components/PostMenu.tsx, src/pages/community/post/components/ReportModal.tsx, src/pages/community/post/components/ViewPost.tsx
- closed #100
- 게시글 등록 및 수정 시 이미지 등록 기능 추가
- 게시글 조회 시 이미지 추가
=> [feat/#100] 게시글 이미지 등록 추가

src/pages/_app.tsx, src/pages/community/components/NoticeModal.tsx, src/pages/community/components/UserNavbar.tsx, src/pages/community/create/index.tsx, src/pages/community/modify/[postId]/index.tsx, src/pages/community/post/[postId]/index.tsx, src/pages/community/post/components/PostMenu.tsx, src/pages/community/post/components/ReportModal.tsx, src/store/useAuthStore.ts, src/store/useModalStore.ts
- closed #103 
- 로그인 전역 상태 관리 추가
- UserNavbar 상태 관리 추가
=> [feat/#103] 로그인 전역상태 처리 및 UserNavbar 로그인 상태 연동

next.config.ts, src/apis/axios-instance.ts, src/components/layout/Header.tsx, src/components/layout/Sidebar.tsx, src/hooks/community/usePostMutation.ts, src/hooks/community/useUserCount.ts, src/pages/_app.tsx, src/pages/community/components/NoticeModal.tsx, src/pages/community/components/UserNavbar.tsx, src/pages/community/create/index.tsx, src/pages/community/modify/[postId]/index.tsx, src/pages/community/post/[postId]/index.tsx, src/pages/community/post/components/CommentInput.tsx, src/pages/community/post/components/CommentItem.tsx, src/pages/community/post/components/CommentList.tsx, src/pages/community/post/components/CommentMenu.tsx, src/pages/community/post/components/PostMenu.tsx, src/pages/community/post/components/ReplyItem.tsx, src/pages/community/post/components/ReportModal.tsx, src/pages/community/post/components/ViewPost.tsx, src/store/useAuthStore.ts, src/store/useModalStore.ts
- closed #105
- 헤더 로그인 상태 연동
- 사이드바 분리 및 리펙토링
- 사이드바 로그인 상태 연동
- 사이드바 애니메이션 추가
=> [feat/#105] 헤더 기능 추가 및 리펙토링

src/apis/auth.ts, src/components/common/MedicineCard.tsx, src/components/common/Search.tsx, src/components/common/SearchModalButton.tsx, src/components/common/SupplementCard.tsx, src/components/layout/AdditionalHeader.tsx, src/components/layout/Header.tsx, src/pages/_app.tsx, src/pages/community/components/SkeletonItem.tsx, src/pages/community/components/UserNavbar.tsx, src/pages/community/post/[postId]/index.tsx, src/pages/community/post/components/CommentInput.tsx, src/pages/community/post/components/CommentItem.tsx, src/pages/community/post/components/CommentList.tsx, src/pages/community/post/components/CommentMenu.tsx, src/pages/community/post/components/PostMenu.tsx, src/pages/community/post/components/ReplyItem.tsx, src/pages/community/post/components/ReportModal.tsx, src/pages/community/post/components/ViewPost.tsx, src/pages/medicines/[medicineId]/index.tsx, src/pages/mypage/index.tsx, src/store/useAuthStore.ts, src/store/useModalStore.ts
- closed #118 
- 마이페이지 userName 연동
=> [feat]#118 마이페이지의 userName api 연동

next.config.ts, src/components/common/SupplementCard.tsx, src/pages/supplements/[supplementId]/index.tsx, src/pages/supplements/components/MoreSupplements.tsx, src/pages/supplements/components/ProductBasicInfo.tsx, src/pages/supplements/index.tsx
- closed #1
- 카테고리 api 연결
- 상세 api 연결
- 북마크 api 연결
- 태그 스크롤 구현
- 검색어 제외하고 연결함!!
영상 녹화로 pm님께 확인받음
=> [feat/#99] 해외인기영양제 api 연결

src/components/common/SupplementCard.tsx, src/pages/supplements/components/ProductBasicInfo.tsx, src/pages/supplements/index.tsx
=> [feat/#99] 영양제의 필요없는 주석 처리

package.json, pnpm-lock.yaml, src/pages/map/components/MapComponent.tsx, src/pages/map/components/MapSearchHeader.tsx, src/pages/map/components/SearchPanel.tsx, src/pages/map/index.tsx
- closed #139 
- 약국 검색기능 구현 
https://github.com/user-attachments/assets/59f9acd5-4a8a-469c-b291-bc282687539b
https://github.com/user-attachments/assets/11936109-0038-4902-8951-9ceb2bc15a38
디바운스 사용해서 구현했습니다
추후에 리팩토링도 최대한 해보겠습니다..,,
=> [feat/#139] 약국찾기 검색기능 구현

src/pages/map/components/IsOpenTag.tsx, src/pages/map/components/MapComponent.tsx, src/pages/map/components/PharmacyItem.tsx, src/pages/map/components/PharmacyList.tsx, src/pages/map/components/detailPanel/Info.tsx, src/pages/map/components/detailPanel/PanelContent.tsx, src/pages/map/components/detailPanel/PharmacyHeader.tsx
- closed #143 
- 약국 상세정보 (사이트, 휠체어정보, 오버뷰) 추가
- 약국 영업중 태그 데이터 수정
- 약국찾기 디자인 피드백 반영
구글맵 플레이스 api에 약국의 상세정보가 대부분 등록되어 있지 않은 경우가 많습니다..
그래서 대부분 정보가 없다고 뜨는데, 기디랑 얘기해보고 추후에 수정하겠습니다
=> [feat/#143] 약국 상세정보 구현

src/components/common/MedicineCard.tsx, src/pages/community/components/PageNavigator.tsx, src/pages/medicines/index.tsx
- closed #154
- 상비약 카드 Image 크기 수정
- 상비약 리스트 페이지 padding 수정
- PageNavigator 반응형 수정
=> [feat/#154] 상비약 페이지 디자인 수정

src/pages/login/index.tsx
- closed #158 
- 로그인 api url 변경
=> [feat]#158🐛 로그인 api 주소 변경

src/components/common/SupplementCard.tsx
=> [feat/#165] 해외인기영양제 페이지 광고 수정

src/pages/community/post/[postId]/index.tsx
- closed #169
- 신고한 게시글 임의 접근 방지
=> [feat/#169] 신고한 게시글 임의 접근 방지

src/components/common/Loader.tsx, src/components/common/MedicineCard.tsx, src/components/common/MedicineCardList.tsx, src/hooks/medicine/useMedicineScrap.ts, src/pages/medicines/components/MedicineDetail.tsx, src/pages/medicines/index.tsx, src/types/medicine.ts
=> [feat/#162] 상비약 저장기능 구현 

src/components/common/SearchModal.tsx, src/pages/community/create/index.tsx, src/pages/community/post/components/CommentInput.tsx
- closed #172 
- 댓글 입력 창 높이 조절 기능 추가
- 상비약 검색 창 국가에서 일본 제거
=> [feat/#172] UI/UX 개선

src/components/common/Search.tsx, src/components/common/SearchModal.tsx, src/components/common/SearchModalButton.tsx, src/pages/mypage/medicines/index.tsx
=> [refactor/#176] 검색창 기능 개선

src/components/common/MedicineCard.tsx, src/hooks/medicine/useMedicineScrap.ts, src/pages/mypage/index.tsx, src/pages/mypage/medicines/index.tsx, src/pages/supplements/[supplementId]/index.tsx, src/pages/supplements/components/MoreSupplements.tsx, src/pages/supplements/components/ProductBasicInfo.tsx, src/pages/supplements/index.tsx, src/types/medicine.ts
- closed #164
[마이페이지]
- 상비약 카드 연결(최대 4개 보이게)
- 마이페이지 스크랩 즉시 안 보이게 반영
[마이페이지-상비약 스크랩 목록 페이지]
- 상비약 스크랩 목록(페이지네이션 연결)
- 스크랩 시 즉시 반영
- 부드럽게 스크롤 추가
- 백 api 수정 --> 다시 확인함
- >> 한국 상비약 추가 시 다시 확인 필요
=> [feat/#164] 마이페이지 상비약 스크랩 연결

src/components/common/SupplementCard.tsx, src/pages/community/components/PostList.tsx, src/pages/community/index.tsx, src/pages/community/post/components/CommentItem.tsx, src/pages/community/post/components/ReplyItem.tsx, src/pages/community/post/components/ReportModal.tsx, src/pages/login/index.tsx, src/pages/mypage/components/PharmacysCard.tsx, src/pages/mypage/pharmacys/index.tsx, src/pages/mypage/supplement/index.tsx, src/pages/supplements/[supplementId]/index.tsx, src/pages/supplements/components/ProductBasicInfo.tsx, src/pages/supplements/index.tsx, src/utils/cookie.ts
- closed #178
- 게시글 랜덤 조회 axios 헤더 설정
=> [refactor/#178] 게시글 랜덤 조회 헤더 설정

src/components/common/SupplementCard.tsx, src/pages/supplements/[supplementId]/index.tsx
- closed #180
- 영양제 스크랩 시 모달 뜨게
카톡방에 녹화영상 보냄
=> [feat/#180] 영양제 유지보수

src/apis/axios-instance.ts, src/components/common/SupplementCard.tsx, src/components/layout/Header.tsx, src/pages/community/activities/components/MyNotificationList.tsx, src/pages/community/components/NoticeModal.tsx, src/pages/community/components/UserNavbar.tsx, src/pages/community/create/index.tsx, src/pages/login/index.tsx, src/pages/mypage/index.tsx, src/pages/supplements/[supplementId]/index.tsx, src/store/useModalStore.ts
- closed #182
- 약국/상비약/영양제 스크랩 시 modal 창 및 로그인 redirect 통일
- 게시글/상비약/영양제 url 복사 시 modal 통일
=> [refactor/#182] 미 로그인 접근 시 modal/redirect 통일

src/components/common/MedicineCard.tsx, src/components/common/PageNavigator.tsx, src/components/common/Search.tsx, src/components/layout/AdditionalHeader.tsx, src/constants/FilterList.ts, src/constants/MedicineCategories.ts, src/hooks/medicine/useMedicineSearch.ts, src/pages/medicines/components/EmptySearchResults.tsx, src/pages/medicines/components/MedicineDetail.tsx, src/pages/medicines/components/MedicineSearchResults.tsx, src/pages/medicines/search/index.tsx
- closed #162 
- 상비약 검색 연동
https://github.com/user-attachments/assets/910816b3-5edd-4b69-9a64-4ca6b2083078
=> [feat/#162] 상비약 검색 연동

src/apis/axios-instance.ts, src/components/common/SupplementCard.tsx, src/pages/supplements/index.tsx
- closed #184
- 영양제 카드 눌렀을 때 문구 잘못 뜨는거 수정
정훈님이 확인함
=> [feat/#184] 스크랩 모달 수정

src/components/common/FilterButtonList.tsx, src/pages/community/post/components/ReportModal.tsx, src/pages/community/posts/search/index.tsx, src/pages/supplements/index.tsx, src/store/useModalStore.ts
- closed #186 
- 검색 후 모바일 필터버튼 클릭 시 라우팅 수정
=> [refactor/#186] 검색 및 필터 버튼 개선
